name: story_groupper
description: "Flutter solution for Stories containing multiple sub-stories"
version: 0.0.1
homepage: https://github.com/SanzharM/flutter_story_groupper.git

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# flutter:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
